/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import DAO.VeiculoDAO;
import Entities.RegistroVeiculo;
import Entities.Veiculo;
import Forms.RegitrosTelas.RegistroTelaVeiculo;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quart
 */
public class TabelaVeiculo extends javax.swing.JFrame {
    RegistroVeiculo registroVeiculo = new RegistroVeiculo();
    
    /**
     * Creates new form TabelaVeiculo
     */
    public TabelaVeiculo() {
        initComponents();
        
        VeiculoDAO veiculoDAO = new VeiculoDAO();
        List<Veiculo> veiculoLista = veiculoDAO.listar();
        preencherTabelaVeiculo(veiculoLista);
        acessibilidadeTabelaVeiculo();
    }
    
    /**
     * Método para preencher a tabela com a lista de objetos do tipo veículo. 
     * Exibe todos os dados de veículo registrados no banco de dados na tabela, preenchendo as colunas 
     * 'ID', 'Marca', 'Modelo', 'Cor, 'Cambio', 'Ano', 'Acéssorios', 'Quilometragem', 'Condição', 'Manutenção', 'Preço', 'Garantia', 
     * 'Registrado por' e 'Data de registro'.
     * 
     * @param veiculo Lista de objetos do tipo veículo a ser exibida na tabela.
     */
    public void preencherTabelaVeiculo(List<Veiculo> veiculo){
        String colunas[] = {"ID","Marca", "Modelo", "Cor", "Cambio", "Ano", "Acéssorios", "Quilometragem", "Condição", "Manutenção", "Preço",
            "Garantia", "Registrado por", "Data de registro"};
        String dados[][] = new String[veiculo.size()][colunas.length];
        
        int i = 0;
        for(Veiculo v : veiculo){
            String nomeFuncionario = "";
            String dataRegistro = "";
            
            if(!v.getRegistroVeiculo().isEmpty()){
                RegistroVeiculo registroVeiculo = v.getRegistroVeiculo().get(0);
                nomeFuncionario = registroVeiculo.getFuncionarioId().getNomeFuncionario();
                dataRegistro = registroVeiculo.getDataRegistro().toString();
            }
            
            dados[i] = new String[]{
                String.valueOf(v.getIdVeiculo()),
                v.getMarcaVeiculo(),
                v.getModeloVeiculo(),
                v.getCorVeiculo(),
                v.getCambioVeiculo(),
                String.valueOf(v.getAnoVeiculo()),
                v.getAcessorios(),
                String.valueOf(v.getQuilometragem()),
                v.getCondicaoVeiculo(),
                v.getStatusManutencao(),
                String.valueOf(v.getPrecoVeiculo()),
                v.getGarantia(),
                nomeFuncionario,
                dataRegistro
            };
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(dados, colunas);
        tblVeiculo.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVeiculo = new javax.swing.JTable();
        btnExcluirVeiculo = new javax.swing.JButton();
        btnRegistrarVeiculo1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itSairRegistroVeiculo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        tblVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblVeiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Marca", "Modelo", "Cor", "Cambio", "Ano", "Acessórios", "Quilometragem", "Condição", "Manutençao", "Preço", "Garantia", "Registrado por", "Data de registro"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVeiculo);

        btnExcluirVeiculo.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluirVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExcluirVeiculo.setText("Excluir");
        btnExcluirVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirVeiculoActionPerformed(evt);
            }
        });

        btnRegistrarVeiculo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrarVeiculo1.setText("Registrar Veículo");
        btnRegistrarVeiculo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVeiculo1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");

        itSairRegistroVeiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        itSairRegistroVeiculo.setText("Sair");
        itSairRegistroVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itSairRegistroVeiculoActionPerformed(evt);
            }
        });
        jMenu1.add(itSairRegistroVeiculo);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1329, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluirVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(btnRegistrarVeiculo1)
                    .addContainerGap(1177, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExcluirVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(433, Short.MAX_VALUE)
                    .addComponent(btnRegistrarVeiculo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação para sair da tabela e retornar ao menu principal.
     * 
     * @param evt Evento disparado pela ação do botão.
     */
    private void itSairRegistroVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSairRegistroVeiculoActionPerformed
        dispose();
    }//GEN-LAST:event_itSairRegistroVeiculoActionPerformed

    /**
     * Ação para sair da tabela e ir para a tela de cadastro de veículos.
     * 
     * @param evt Evento disparado pela ação do botão.
     */
    private void btnExcluirVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirVeiculoActionPerformed
       try{
           int linhaSelecionada = tblVeiculo.getSelectedRow();
           
           if(linhaSelecionada >= 0){
               Object idObjetoVeiculo = (String)tblVeiculo.getValueAt(tblVeiculo.getSelectedRow(), 0);
               int id = Integer.parseInt(idObjetoVeiculo.toString());
               
               int resposta = JOptionPane.showConfirmDialog(this, "Deseja mesmo excluir o registro " + id + "?");
               if(resposta == JOptionPane.YES_OPTION){
                   VeiculoDAO veiculoDAO = new VeiculoDAO();
                   veiculoDAO.excluirVeiculo((id));
                   JOptionPane.showMessageDialog(this, "Registro excluído com sucesso");
                   
                   DefaultTableModel modelo = (DefaultTableModel) tblVeiculo.getModel();
                   modelo.removeRow(linhaSelecionada);
               }
               
           }
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(this, "Ocorreu uma falha:\n" + e.getMessage());
       }
    }//GEN-LAST:event_btnExcluirVeiculoActionPerformed

    private void btnRegistrarVeiculo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVeiculo1ActionPerformed
        RegistroTelaVeiculo registroTelaVeiculo = new RegistroTelaVeiculo();
        registroTelaVeiculo.setVisible(true);
    }//GEN-LAST:event_btnRegistrarVeiculo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirVeiculo;
    private javax.swing.JButton btnRegistrarVeiculo1;
    private javax.swing.JMenuItem itSairRegistroVeiculo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVeiculo;
    // End of variables declaration//GEN-END:variables

    /**
     * Método de acessibilidade, acessa a tela de cadastro de veículos usando ALT + C.
     */
    private void acessibilidadeTabelaVeiculo(){
        btnExcluirVeiculo.setMnemonic(KeyEvent.VK_C);
    }
   
}
