/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;


import DAO.RegistroVendaDAO;
import Entities.RegistroVenda;
import Forms.RegitrosTelas.RegistroVendaCarro;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author quart
 */
public class TabelaVenda extends javax.swing.JFrame {
    
    /**
     * Creates new form TabelaVenda
     */
    public TabelaVenda() {
        initComponents();
        preencherTabelaVenda();
        acessibilidadeTabelaVenda();
    }
    
    private void preencherTabelaVenda(){
        RegistroVendaDAO registroVendaDAO = new RegistroVendaDAO();
        List<RegistroVenda> vendaLista = registroVendaDAO.getVenda();
        preencherTabelaVenda(vendaLista);
    } 
    
    /**
     * Método para preencher a tabela com a lista de objetos do tipo venda. 
     * Exibe todos os dados de vendas registrados no banco de dados na tabela, preenchendo as colunas 
     * 'ID', 'Veiculo', 'Cliente', 'Funcionario', 'Data de venda'
     * 
     * @param venda Lista de objetos do tipo vendas a ser exibida na tabela.
     */
    public void preencherTabelaVenda(List<RegistroVenda> venda){
        String colunas[] = {"ID", "Veiculo", "Cliente", "Funcionario", "Data de venda"};
        String dados[][] = new String[venda.size()][colunas.length];
        
        int i = 0;
        for(RegistroVenda rv : venda){
            dados[i] = new String[]{
                String.valueOf(rv.getIdRegistroVenda()),
                String.valueOf(rv.getVeiculos()),
                String.valueOf(rv.getFuncionario()),
                String.valueOf(rv.getCliente()),
                String.valueOf(rv.getDataRegistro())    
            };
            i++;
        }
        DefaultTableModel model = new DefaultTableModel(dados, colunas);
        tblVendas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVendas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
        btnRegistrarVendas = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        itSair = new javax.swing.JMenu();
        itVoltar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblVendas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Veículo", "Cliente", "Funcionário", "Data de venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblVendas.setToolTipText("");
        jScrollPane1.setViewportView(tblVendas);

        btnRegistrarVendas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrarVendas.setText("Registrar Vendas");
        btnRegistrarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVendasLayout = new javax.swing.GroupLayout(pnlVendas);
        pnlVendas.setLayout(pnlVendasLayout);
        pnlVendasLayout.setHorizontalGroup(
            pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVendasLayout.createSequentialGroup()
                .addComponent(btnRegistrarVendas)
                .addGap(0, 427, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        pnlVendasLayout.setVerticalGroup(
            pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVendasLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        itSair.setText("Menu");

        itVoltar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        itVoltar.setText("Voltar");
        itVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itVoltarActionPerformed(evt);
            }
        });
        itSair.add(itVoltar);

        jMenuBar2.add(itSair);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação para abrir tela de cadastro de vendas.
     * 
     * @param evt Evento disparado pela ação do botão.
     */
    private void btnRegistrarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVendasActionPerformed
        RegistroVendaCarro registroVendaCarro = new RegistroVendaCarro();
        registroVendaCarro.setVisible(true);
    }//GEN-LAST:event_btnRegistrarVendasActionPerformed

    /**
     * Ação para sair da tabela e retornar ao menu principal.
     * 
     * @param evt Evento disparado pela ação do botão.
     */
    private void itVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_itVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarVendas;
    private javax.swing.JMenu itSair;
    private javax.swing.JMenuItem itVoltar;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlVendas;
    private javax.swing.JTable tblVendas;
    // End of variables declaration//GEN-END:variables
  
    /**
     * Método de acessibilidade, acessa a tela de cadastro de vendas usando ALT + C.
     */
    private void acessibilidadeTabelaVenda(){
        btnRegistrarVendas.setMnemonic(KeyEvent.VK_C);
    }
}
