package Forms;

import DAO.ClienteDAO;
import Entities.Cliente;
import Forms.RegitrosTelas.RegistroCliente;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author quart
 */
public class TabelaCliente extends javax.swing.JFrame {
    RegistroCliente registroCliente = new RegistroCliente();
    
    /**
     * Creates new form TabelaCliente
     */
    public TabelaCliente() {
        initComponents();
        ClienteDAO clienteDAO = new ClienteDAO();
        List<Cliente> cliente = clienteDAO.getCliente();
        PreencherTabelaCliente(cliente);
        acessibilidadeTabelaCliente();
    }

    /**
     * Método para preencher a tabela com a lista de objetos do tipo cliente. 
     * Exibe todos os dados de cliente registrados no banco de dados na tabela, preenchendo as colunas 'ID', 'Nome', 'Telefone', 'CPF'.
     * 
     * @param listaCliente Lista de objetos do tipo Cliente a ser exibida na tabela.
     */
    public void PreencherTabelaCliente(List<Cliente> listaCliente){
        String colunas[] = {"ID", "Nome", "Telefone", "CPF"};
        String dadosCliente[][] = new String[listaCliente.size()][colunas.length];
        
        int i = 0;
        for(Cliente c : listaCliente){
            dadosCliente[i] = new String[]{
            String.valueOf(c.getIdCliente()),
            c.getNomeCliente(),
            c.getTelefone(),
            c.getCPF()
            };
            i++;
        }
        DefaultTableModel tableModel = new DefaultTableModel(dadosCliente, colunas);
        tblCliente.setModel(tableModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistroCliente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        btnRegistrarCliente = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        tblCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCliente);

        btnRegistrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegistroClienteLayout = new javax.swing.GroupLayout(pnlRegistroCliente);
        pnlRegistroCliente.setLayout(pnlRegistroClienteLayout);
        pnlRegistroClienteLayout.setHorizontalGroup(
            pnlRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegistroClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrarCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        pnlRegistroClienteLayout.setVerticalGroup(
            pnlRegistroClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegistroClienteLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Menu");

        itSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        itSair.setText("Sair");
        itSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itSairActionPerformed(evt);
            }
        });
        jMenu1.add(itSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação para sair da tabela e retornar ao menu principal.
     * @param evt 
     */
    private void itSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSairActionPerformed
       dispose();
    }//GEN-LAST:event_itSairActionPerformed

    /**
     * Ação para sair da tabela e entrar na tela de cadastro de clientes.
     * 
     * @param evt Evento disparado pela ação do botão.
     */
    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
       RegistroCliente registroCliente = new RegistroCliente();
       registroCliente.setVisible(true);
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JMenuItem itSair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlRegistroCliente;
    private javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables

    /**
     * Método de acessibilidade, acessa a tela de cadastro de clientes usando ALT + C.
     */
    private void acessibilidadeTabelaCliente(){
        btnRegistrarCliente.setMnemonic(KeyEvent.VK_C);
    }
}
