/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import DAO.FuncionarioDAO;
import Entities.Cargo;
import Entities.Funcionarios;
import Forms.RegitrosTelas.RegistroFuncionario;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author quart
 */
public class TabelaFuncionario extends javax.swing.JFrame {
    RegistroFuncionario registroFuncionario = new RegistroFuncionario();
    /**
     * Creates new form TabelaFuncionario
     */
    public TabelaFuncionario() {
        initComponents();
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        List<Funcionarios> funcionario = funcionarioDAO.listar();
        preencherTabelaFuncionario(funcionario);
        AcessibilidadeTabelaFuncionario();
    }

    /**
     * Método para preencher a tabela com a lista de objetos do tipo funcionario. 
     * Exibe todos os dados de funcionarios registrados no banco de dados na tabela, preenchendo as colunas 
     * 'ID', 'Nome', 'Telefone', 'CPF', 'Cargo', 'Login' e 'Senha'.
     * 
     * @param funcionario Lista de objetos do tipo funcionário a ser exibida na tabela.
     */
    public void preencherTabelaFuncionario(List<Funcionarios> funcionario){
        String colunas[] = {"ID", "Nome", "Telefone", "CPF", "Cargo", "Login", "Senha"};
        String dadosFuncionario[][] = new String[funcionario.size()][colunas.length];
       
        int i = 0;
        for(Funcionarios f : funcionario){
            String cargoNome = "";
            
            if(f.getCargo() != null){
                Cargo cargo = f.getCargo();
                cargoNome = cargo.getTipoCargo().getDescricao();
            }
            
            dadosFuncionario[i] = new String[]{
                String.valueOf(f.getIdFuncionario()),
                f.getNomeFuncionario(),
                f.getTelefone(),
                f.getCPF(),
                cargoNome,
                f.getLoginFuncionario().getLogin(),
                f.getLoginFuncionario().getSenha()
            };
            i++;
        }
        DefaultTableModel tableModel = new DefaultTableModel(dadosFuncionario, colunas);
        tblFuncionario.setModel(tableModel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTabelaFuncionario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionario = new javax.swing.JTable();
        btnRegistrarFuncionario = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        tblFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone", "CPF", "Cargo", "Login", "Senha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFuncionario);

        btnRegistrarFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrarFuncionario.setText("Registrar Funcinário");
        btnRegistrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabelaFuncionarioLayout = new javax.swing.GroupLayout(pnlTabelaFuncionario);
        pnlTabelaFuncionario.setLayout(pnlTabelaFuncionarioLayout);
        pnlTabelaFuncionarioLayout.setHorizontalGroup(
            pnlTabelaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelaFuncionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegistrarFuncionario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
        );
        pnlTabelaFuncionarioLayout.setVerticalGroup(
            pnlTabelaFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabelaFuncionarioLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        itSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        itSair.setText("Sair");
        itSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itSairActionPerformed(evt);
            }
        });
        jMenu1.add(itSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTabelaFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTabelaFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação para sair da tabela e ir para a tela de cadastro de funcionários.
     * 
     * @param evt Evento disparado pela ação do botão. 
     */
    private void btnRegistrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarFuncionarioActionPerformed
        RegistroFuncionario registroFuncionario = new RegistroFuncionario();
        registroFuncionario.setVisible(true);
    }//GEN-LAST:event_btnRegistrarFuncionarioActionPerformed

    /**
     * Ação para sair da tabela e retornar ao menu principal.
     * 
     * @param evt Evento disparado pela ação do botão.
     */
    private void itSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itSairActionPerformed
        dispose();
    }//GEN-LAST:event_itSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarFuncionario;
    private javax.swing.JMenuItem itSair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlTabelaFuncionario;
    private javax.swing.JTable tblFuncionario;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Método de acessibilidade, acessa a tela de cadastro de funcionários usando ALT + C.
     */
    private void AcessibilidadeTabelaFuncionario(){
        btnRegistrarFuncionario.setMnemonic(KeyEvent.VK_C);
    }
}
