/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms.RegitrosTelas;



import DAO.ClienteDAO;
import DAO.FuncionarioDAO;
import DAO.RegistroVendaDAO;
import DAO.VeiculoDAO;
import Entities.Cliente;
import Entities.Funcionarios;
import Entities.RegistroVenda;
import Entities.Veiculo;
import Forms.TabelaVenda;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;



/**
 *
 * @author quart
 */
public class RegistroVendaCarro extends javax.swing.JFrame {
    
    /**
     * Creates new form RegistroVenda
     */
    public RegistroVendaCarro() {
        initComponents();
        preencherCombo();
        acessibilidadeVenda();
    }
    
    /**
     * Preenche as combobox com veículos, clientes e funcionários registrados no banco de dados.
     * O método recupera as listas de cada objeto disponível no banco de dados e adiciona-os em cada combobox.
     */
    public void preencherCombo(){
         preencherComboVeiculo();
         preencherComboCliente();
         preencherComboFuncionario();
    }
    
    private void preencherComboVeiculo(){
        cbxVeiculo.addItem("Veículo");
        VeiculoDAO veiculoDao = new VeiculoDAO();
        List<Veiculo> veiculos = veiculoDao.listar();
        for(Veiculo v: veiculos){
            cbxVeiculo.addItem(v);
        }
    }
    
    private void preencherComboCliente(){
        cbxCliente.addItem("Cliente");
        ClienteDAO clienteDao = new ClienteDAO();
        List<Cliente> clientes = clienteDao.listar();
        for(Cliente c : clientes){
            cbxCliente.addItem(c);
        }
    }
    
    private void preencherComboFuncionario(){
        cbxFuncionario.addItem("Funcionário");
        FuncionarioDAO funcionarioDao = new FuncionarioDAO();
        List<Funcionarios> funcionarios = funcionarioDao.listar();
        for(Funcionarios f : funcionarios){
            cbxFuncionario.addItem(f);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblVeiculo = new javax.swing.JLabel();
        cbxVeiculo = new javax.swing.JComboBox();
        lblFuncionario = new javax.swing.JLabel();
        cbxCliente = new javax.swing.JComboBox();
        lblCliente = new javax.swing.JLabel();
        cbxFuncionario = new javax.swing.JComboBox();
        btnRegistarVenda = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itVoltar = new javax.swing.JMenuItem();
        itLimpar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Registro Venda");

        lblVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblVeiculo.setText("Veículo:");

        cbxVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxVeiculo.setToolTipText("qual veículo foi vendido.");

        lblFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblFuncionario.setText("Funcionário:");

        cbxCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxCliente.setToolTipText("Qual cliente esta comprando.");

        lblCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCliente.setText("Cliente:");

        cbxFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxFuncionario.setToolTipText("Qual funcionário realizou a venda.");

        btnRegistarVenda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistarVenda.setText("Registrar");
        btnRegistarVenda.setToolTipText("Registra a venda.");
        btnRegistarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegistarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente)
                            .addComponent(jLabel1)
                            .addComponent(lblFuncionario)
                            .addComponent(lblVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbxVeiculo, 0, 227, Short.MAX_VALUE)
                            .addComponent(cbxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbxFuncionario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVeiculo)
                    .addComponent(cbxVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuncionario)
                    .addComponent(cbxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        jMenu1.setText("Opções");

        itVoltar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        itVoltar.setText("Voltar");
        itVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itVoltarActionPerformed(evt);
            }
        });
        jMenu1.add(itVoltar);

        itLimpar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        itLimpar.setText("Limpar");
        itLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itLimparActionPerformed(evt);
            }
        });
        jMenu1.add(itLimpar);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação responsável por cadastrar um objeto do tipo venda no banco de dados.
     * Pressionando o botão, ele valida os campos e depois realiza a inserção da venda no banco de dados.
     * 
     * @param evt Evento disparado pela ação do botão.
     */
    private void btnRegistarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarVendaActionPerformed
       RegistroVenda registroVenda = new RegistroVenda();
       
        if(!validacaoVenda()){
           Veiculo veiculoSelecionado = (Veiculo) cbxVeiculo.getSelectedItem();
           Cliente clienteSelecionado = (Cliente) cbxCliente.getSelectedItem();
           Funcionarios funcionarioSelecionado = (Funcionarios) cbxFuncionario.getSelectedItem();
           
           registroVenda.setCliente(clienteSelecionado);
           registroVenda.setFuncionario(funcionarioSelecionado);
           registroVenda.setDataRegistro(LocalDate.now());
           registroVenda.setVeiculos(Arrays.asList(veiculoSelecionado));
           veiculoSelecionado.setRegistroVenda(Arrays.asList(registroVenda));
           
           try{
                RegistroVendaDAO registroVendaDAO = new RegistroVendaDAO();
                registroVendaDAO.cadastrarVenda(registroVenda);
           
                JOptionPane.showMessageDialog(rootPane, "A venda foi registrada.");
           
                cbxVeiculo.setSelectedIndex(0);
                cbxCliente.setSelectedIndex(0);
                cbxFuncionario.setSelectedIndex(0);
           }
           catch(Exception e){
              JOptionPane.showMessageDialog(rootPane, "Erro ao cadastrar a venda");
              return;
           }
          
        }
       else{
           return;
       }
    }//GEN-LAST:event_btnRegistarVendaActionPerformed

    /**
     * Ação para sair da tela de registro vendas.
     * 
     * @param evt Evento disparado pela ação do botão.
     */
    private void itVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itVoltarActionPerformed
       dispose();
    }//GEN-LAST:event_itVoltarActionPerformed

    /**
     * Essa ação é responsavel por redefir os valores da combobox.
     * 
     * @param evt Evento disparado pela ação do botão.
     */
    private void itLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itLimparActionPerformed
        cbxVeiculo.setSelectedIndex(0);
        cbxCliente.setSelectedIndex(0);
        cbxFuncionario.setSelectedIndex(0);
    }//GEN-LAST:event_itLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroVendaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroVendaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroVendaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroVendaCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroVendaCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistarVenda;
    private javax.swing.JComboBox cbxCliente;
    private javax.swing.JComboBox cbxFuncionario;
    private javax.swing.JComboBox cbxVeiculo;
    private javax.swing.JMenuItem itLimpar;
    private javax.swing.JMenuItem itVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblVeiculo;
    // End of variables declaration//GEN-END:variables
    
    public TabelaVenda tabelaVenda;
    
    /**
     * Válida se as combobox estão com o valor padrão.
     * 
     * Esté método verifica se as combobox possuem valores diferentes do padrão (índice 0).
     * Se as combobox não forem selecionadas, será apresentado uma das mensagens na tela.
     * 
     * @return 'false' se as combox forem selecionadas, 'true' contrário.
     */
    private boolean validacaoVenda(){
        boolean vazio = true;
        
        if(cbxVeiculo.getSelectedIndex() == 0 && cbxCliente.getSelectedIndex() == 0 && cbxFuncionario.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(rootPane, "Você precisa escolher o veículo, cliente e funcionário");
        }
        else if(cbxVeiculo.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(rootPane, "Você precisa selecionar o veículo que foi vendido");
        }
        else if(cbxCliente.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(rootPane, "Você precisa selecionar o cliente que comprou o veículo");
        }
        else if(cbxFuncionario.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(rootPane,"Você precisa selecionar o funcionário que realizou a venda.");
        }
        else{
            vazio = false;
        }
        
        return vazio;
    }
    
    /**
     * Realiza o registro usando ALT+D.
     */
    private void acessibilidadeVenda(){
        btnRegistarVenda.setMnemonic(KeyEvent.VK_D);
    }
}

