/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms.RegitrosTelas;


import DAO.FuncionarioDAO;
import DAO.VeiculoDAO;
import Entities.Funcionarios;
import Entities.RegistroVeiculo;
import Entities.Veiculo;
import Forms.TabelaVeiculo;
import java.awt.CardLayout;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.Year;
import java.util.Arrays;
import java.util.List;

import javax.swing.JOptionPane;


/**
 *
 * @author quart
 */
public class RegistroTelaVeiculo extends javax.swing.JFrame {
    
    /**
     * Creates new form RegistroVeiculo
     */
    public RegistroTelaVeiculo() {
        initComponents();
        preencherComboFuncionario();
        Acessibilidade();
        
        pnlRegistroVeiculo.revalidate();
        pnlRegistroVeiculo.repaint();
    }

    /**
     * Preenche a combobox com funcionários registrados no banco de dados.
     * O método recupera alista de cargos disponível no banco de dados e adiciona a na combobox 'cbxFuncionario'
     */
    public void preencherComboFuncionario(){
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        cbxFuncionario.addItem("Funcionario");
        
        List<Funcionarios> funcionarios = funcionarioDAO.listar();
        
        for(Funcionarios f : funcionarios){
            cbxFuncionario.addItem(f);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRegistroVeiculo = new javax.swing.JPanel();
        Pagina1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        txtCambio = new javax.swing.JTextField();
        lblCambio = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        lblAcessorios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAcessorios = new javax.swing.JTextArea();
        lblQuilometragem = new javax.swing.JLabel();
        txtQuilometragem = new javax.swing.JTextField();
        btnProximaPagina = new javax.swing.JButton();
        Pagina2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblCondicao = new javax.swing.JLabel();
        txtCondicao = new javax.swing.JTextField();
        lblManutencao = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        lblPreco = new javax.swing.JLabel();
        txtManutencao = new javax.swing.JTextField();
        lblGarantia = new javax.swing.JLabel();
        txtGarantia = new javax.swing.JTextField();
        lblRegistradoPor = new javax.swing.JLabel();
        btnRegistrarVeiculo = new javax.swing.JButton();
        btnPaginaAnterior = new javax.swing.JButton();
        cbxFuncionario = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itVoltar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro de Veículo");
        setUndecorated(true);

        pnlRegistroVeiculo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlRegistroVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlRegistroVeiculo.setLayout(new java.awt.CardLayout());

        Pagina1.setToolTipText("Cadastro do Veículo: Etapa 1 de 2");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Registro de veículos");

        lblMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMarca.setLabelFor(txtMarca);
        lblMarca.setText("Marca:");

        txtMarca.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMarca.setToolTipText("Qual a marca do veículo.");

        lblModelo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblModelo.setLabelFor(txtModelo);
        lblModelo.setText("Modelo:");

        txtModelo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtModelo.setToolTipText("Qual modelo do veículo.");

        lblCor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCor.setLabelFor(txtCor);
        lblCor.setText("Cor:");

        txtCambio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCambio.setToolTipText("Qual o tipo do cambio do veículo.");

        lblCambio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCambio.setLabelFor(txtCambio);
        lblCambio.setText("Cambio:");

        txtCor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCor.setToolTipText("Qual cor do veículo");

        lblAno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAno.setLabelFor(txtAno);
        lblAno.setText("Ano:");

        txtAno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtAno.setToolTipText("Qual ano de fabricação");

        lblAcessorios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblAcessorios.setLabelFor(txtAcessorios);
        lblAcessorios.setText("Acessórios:");

        txtAcessorios.setColumns(20);
        txtAcessorios.setRows(5);
        txtAcessorios.setToolTipText("Quais acessórios o veículo possui.");
        txtAcessorios.setNextFocusableComponent(txtQuilometragem);
        jScrollPane1.setViewportView(txtAcessorios);
        txtAcessorios.getAccessibleContext().setAccessibleName("Acessórios");

        lblQuilometragem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuilometragem.setLabelFor(txtQuilometragem);
        lblQuilometragem.setText("Quilometragem:");

        txtQuilometragem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtQuilometragem.setToolTipText("Qual a quilometragem do veículo");

        btnProximaPagina.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnProximaPagina.setText("Próxima Página");
        btnProximaPagina.setToolTipText("Ir para a próxima Pagína");
        btnProximaPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximaPaginaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pagina1Layout = new javax.swing.GroupLayout(Pagina1);
        Pagina1.setLayout(Pagina1Layout);
        Pagina1Layout.setHorizontalGroup(
            Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pagina1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pagina1Layout.createSequentialGroup()
                        .addGroup(Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Pagina1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnProximaPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pagina1Layout.createSequentialGroup()
                                .addComponent(lblMarca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pagina1Layout.createSequentialGroup()
                                .addComponent(lblModelo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pagina1Layout.createSequentialGroup()
                                .addComponent(lblCor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pagina1Layout.createSequentialGroup()
                                .addComponent(lblAno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pagina1Layout.createSequentialGroup()
                                .addComponent(lblCambio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pagina1Layout.createSequentialGroup()
                                .addComponent(lblAcessorios)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pagina1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(Pagina1Layout.createSequentialGroup()
                        .addComponent(lblQuilometragem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQuilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        Pagina1Layout.setVerticalGroup(
            Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pagina1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCor)
                    .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCambio)
                    .addComponent(txtCambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAno)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAcessorios)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuilometragem)
                    .addComponent(txtQuilometragem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnProximaPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtMarca.getAccessibleContext().setAccessibleName("");
        txtModelo.getAccessibleContext().setAccessibleName("");
        txtCambio.getAccessibleContext().setAccessibleName("");
        txtCor.getAccessibleContext().setAccessibleName("");
        txtAno.getAccessibleContext().setAccessibleName("");
        txtQuilometragem.getAccessibleContext().setAccessibleName("Quilometragem");

        pnlRegistroVeiculo.add(Pagina1, "Pagina 1");
        Pagina1.getAccessibleContext().setAccessibleName("Pagina 1 de Registro Veiculo");
        Pagina1.getAccessibleContext().setAccessibleDescription("");

        Pagina2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pagina2.setToolTipText("Página de Registro do Veículo - Etapa 2");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Pagina 2");

        lblCondicao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCondicao.setLabelFor(txtCondicao);
        lblCondicao.setText("Condição:");

        txtCondicao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCondicao.setToolTipText("Qual condição do veículo (Semi Novo, novo, usado  etc.).");

        lblManutencao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblManutencao.setLabelFor(txtManutencao);
        lblManutencao.setText("Manutenção:");

        txtPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPreco.setToolTipText("Qual valor do veículo");

        lblPreco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPreco.setLabelFor(txtPreco);
        lblPreco.setText("Preço: ");
        lblPreco.setToolTipText("");

        txtManutencao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtManutencao.setToolTipText("Como está a manutenção do veículo?");

        lblGarantia.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGarantia.setLabelFor(txtGarantia);
        lblGarantia.setText("Garantia:");

        txtGarantia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGarantia.setToolTipText("Qual a garantia do veículo (da fabricante, da loja ou não tem).");

        lblRegistradoPor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRegistradoPor.setLabelFor(cbxFuncionario);
        lblRegistradoPor.setText("Registrado por");

        btnRegistrarVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRegistrarVeiculo.setText("Registrar");
        btnRegistrarVeiculo.setToolTipText("Registra o veículo.");
        btnRegistrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVeiculoActionPerformed(evt);
            }
        });

        btnPaginaAnterior.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPaginaAnterior.setText("Página Anterior");
        btnPaginaAnterior.setToolTipText("Volta para a pagina anterior.");
        btnPaginaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaAnteriorActionPerformed(evt);
            }
        });

        cbxFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbxFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pagina2Layout = new javax.swing.GroupLayout(Pagina2);
        Pagina2.setLayout(Pagina2Layout);
        Pagina2Layout.setHorizontalGroup(
            Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pagina2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pagina2Layout.createSequentialGroup()
                        .addComponent(btnPaginaAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistrarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pagina2Layout.createSequentialGroup()
                        .addComponent(lblCondicao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pagina2Layout.createSequentialGroup()
                        .addComponent(lblManutencao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addComponent(txtManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pagina2Layout.createSequentialGroup()
                        .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblGarantia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblPreco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegistradoPor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPreco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtGarantia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(cbxFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        Pagina2Layout.setVerticalGroup(
            Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pagina2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCondicao)
                    .addComponent(txtCondicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManutencao)
                    .addComponent(txtManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPreco)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGarantia)
                    .addComponent(txtGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistradoPor)
                    .addComponent(cbxFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addGroup(Pagina2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPaginaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        txtCondicao.getAccessibleContext().setAccessibleName("Condição");
        txtPreco.getAccessibleContext().setAccessibleName("Preço");
        txtManutencao.getAccessibleContext().setAccessibleName("Manutenção");
        txtGarantia.getAccessibleContext().setAccessibleName("Garantia");

        pnlRegistroVeiculo.add(Pagina2, "Pagina2");

        jMenuBar1.setBorder(null);

        jMenu1.setText("Menu");

        itVoltar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        itVoltar.setText("Voltar");
        itVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itVoltarActionPerformed(evt);
            }
        });
        jMenu1.add(itVoltar);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jMenuItem2.setText("Limpar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistroVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRegistroVeiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ação para sair da tela da registro de veículos.
     * 
     * @param evt Evento disparado pela ação do botão.
     */
    private void itVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_itVoltarActionPerformed

    /**
     * Ação para avançar para a proxima tela de registroVeiculo.
     * @param evt Evento disparado pela ação do botão.
     */
    private void btnProximaPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximaPaginaActionPerformed
        CardLayout pagina2 = (CardLayout) pnlRegistroVeiculo.getLayout();
        pagina2.next(pnlRegistroVeiculo);
    }//GEN-LAST:event_btnProximaPaginaActionPerformed

    /**
     * Essa ação é responsavel por limpar os campos de texto.
     * @param evt Evento disparado pela ação do botão.
     */
    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        txtMarca.setText("");
        txtModelo.setText("");
        txtCor.setText("");
        txtCambio.setText("");
        txtAno.setText("");
        txtAcessorios.setText("");
        txtQuilometragem.setText("");
        txtCondicao.setText("");
        txtManutencao.setText("");
        txtPreco.setText("");
        txtGarantia.setText("");
        cbxFuncionario.setSelectedIndex(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * Ação responsável por cadastrar um objeto do tipo veículo no banco de dados.
     * Pressionando o botão, ele valida os campos e depois realiza a inserção do veículo no banco de dados.
     * 
     * @param evt Evento disparado pela ação do botão.
     */
    private void btnRegistrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVeiculoActionPerformed
        Veiculo veiculo = new Veiculo();
        RegistroVeiculo registroVeiculo = new RegistroVeiculo();
        
        if(!validacaoVeiculo()){
            try{
                veiculo.setMarcaVeiculo(txtMarca.getText());
                veiculo.setModeloVeiculo(txtModelo.getText());
                veiculo.setCorVeiculo(txtCor.getText());
                veiculo.setCambioVeiculo(txtCambio.getText());
                veiculo.setAnoVeiculo(Year.parse(txtAno.getText()));
                veiculo.setAcessorios(txtAcessorios.getText());
                veiculo.setQuilometragem(Double.valueOf(txtQuilometragem.getText()));
                veiculo.setCondicaoVeiculo(txtCondicao.getText());
                veiculo.setStatusManutencao(txtCondicao.getText());
                veiculo.setPrecoVeiculo(Double.valueOf(txtPreco.getText()));
                veiculo.setGarantia(txtGarantia.getText());
                
                Funcionarios FuncionarioSelecionado = (Funcionarios) cbxFuncionario.getSelectedItem();
                registroVeiculo.setFuncionarioId(FuncionarioSelecionado);
                registroVeiculo.setDataRegistro(LocalDate.now());
                
                registroVeiculo.setVeiculos(Arrays.asList(veiculo)); 
                veiculo.setRegistroVeiculo(Arrays.asList(registroVeiculo));
                
                VeiculoDAO veiculoDAO = new VeiculoDAO();
                veiculoDAO.cadastrarVeiculo(veiculo);
                
                JOptionPane.showMessageDialog(rootPane, "O veículo foi registrado.");
                
                txtMarca.setText("");
                txtModelo.setText("");
                txtCor.setText("");
                txtCambio.setText("");
                txtAno.setText("");
                txtAcessorios.setText("");
                txtQuilometragem.setText("");
                txtCondicao.setText("");
                txtManutencao.setText("");
                txtPreco.setText("");
                txtGarantia.setText("");
                cbxFuncionario.setSelectedIndex(0);
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(rootPane, "Os campos Quilometragem e Preço devem conter apenas números. Por favor, ");
            }
        }
    }//GEN-LAST:event_btnRegistrarVeiculoActionPerformed

    /**
     * Ação Responsavel por volta a tela anterior de registro veiculo.
     * 
     * @param evt Evento disparado pela ação do botão.
     */
    private void btnPaginaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaAnteriorActionPerformed
        CardLayout pagina1 = (CardLayout) pnlRegistroVeiculo.getLayout();
        pagina1.previous(pnlRegistroVeiculo);
    }//GEN-LAST:event_btnPaginaAnteriorActionPerformed

    private void cbxFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroTelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroTelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroTelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroTelaVeiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroTelaVeiculo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pagina1;
    private javax.swing.JPanel Pagina2;
    private javax.swing.JButton btnPaginaAnterior;
    private javax.swing.JButton btnProximaPagina;
    private javax.swing.JButton btnRegistrarVeiculo;
    private javax.swing.JComboBox cbxFuncionario;
    private javax.swing.JMenuItem itVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAcessorios;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCambio;
    private javax.swing.JLabel lblCondicao;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblGarantia;
    private javax.swing.JLabel lblManutencao;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblQuilometragem;
    private javax.swing.JLabel lblRegistradoPor;
    private javax.swing.JPanel pnlRegistroVeiculo;
    private javax.swing.JTextArea txtAcessorios;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtCambio;
    private javax.swing.JTextField txtCondicao;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtGarantia;
    private javax.swing.JTextField txtManutencao;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuilometragem;
    // End of variables declaration//GEN-END:variables
    
    private TabelaVeiculo tabelaVeiculo;
    
    /**
     * Válida os campos Marca, Modelo, Cor, Cambio, Ano, Acessórios, Quilometragem, Condição, Manutenção, Preço, Garantia
     * verificando se eles estão no formato correto, verifica se foi a comboBox foi selecionada.
     * 
     * Se os campos não estiverem no formato correto ou se a combobox não foi selecionada, será apresentado uma das mensagens na tela.
     * 
     * @return 'true' se os campos  estiverem corretos e a combobox selecionada., 'false' contrário.
     */
    private boolean validacaoVeiculo(){
        boolean vazio = true;
        
        String anoTexto = txtAno.getText();
        boolean anoValido = anoTexto.matches("\\d{4}");
       
        if(txtMarca.getText().isEmpty() && txtModelo.getText().isEmpty() && txtCor.getText().isEmpty() && txtCambio.getText().isEmpty() &&
                txtAno.getText().isEmpty() && txtAcessorios.getText().isEmpty() && txtQuilometragem.getText().isEmpty() &&
                txtCondicao.getText().isEmpty() && txtManutencao.getText().isEmpty() && txtPreco.getText().isEmpty() &&
                txtGarantia.getText().isEmpty() && cbxFuncionario.getSelectedIndex() == 0){
            
            JOptionPane.showMessageDialog(rootPane, "Você precisa preencher todos os campos, e escolher o funcionário que registrou o veículo.");
        }
        else if(txtMarca.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Você precisa preencher o campo Marca.");
        }
        else if(txtModelo.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Você precisa preencher o campo Modelo.");
        }
        else if(txtCor.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Você precisa preencher o campo Cor.");
        }
        else if(txtCambio.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Você precisa preencher o campo Cambio.");
        }
        else if(txtAno.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Você precisa preencher o campo Ano.");
        }
        else if(txtAcessorios.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Você precisa preencher o campo Acessórios.");
        }
        else if(txtQuilometragem.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Você precisa preencher o campo Quilometragem.");
        }
        else if(txtCondicao.getText().isEmpty()){   
            JOptionPane.showMessageDialog(rootPane, "Você precisa preencher o campo Condição.");
        }
        else if(txtManutencao.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Você precisa preencher o campo Manutenção.");
        }
        else if(txtPreco.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Você precisa preencher o campo Preço.");
        }
        else if(txtGarantia.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Você precisa preencher o campo Garantia.");
        }
        else if(!anoValido){
            JOptionPane.showMessageDialog(rootPane, "O ano inserido é inválido. Por favor, preencha o campo Ano utilizando o formato YYYY.");
        }
        else if(cbxFuncionario.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(rootPane, "Escolha o funcionario que está está fazendo o registro do veículo.");
        }
        else{
            vazio = false;
        }
        
        return vazio;
    }
    
    /**
     * Atalho para realizar a nevagação das paginas e realizar o cadastro.
     */
    public void Acessibilidade(){
        btnProximaPagina.setMnemonic(KeyEvent.VK_E);
        btnPaginaAnterior.setMnemonic(KeyEvent.VK_Q);
        btnRegistrarVeiculo.setMnemonic(KeyEvent.VK_D);
    }
}
